version: "2"
services:
  database:
    image: postgres:9.4-alpine
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=unserewgbot
    volumes:
      - unsere-wg-bot:/var/lib/postgresql/data

volumes:
  unsere-wg-bot: